"""create persistence foundation

Revision ID: 349e932027c8
Revises: 0001_prepare_auth_schema
Create Date: 2026-08-14 12:29:30.381198
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '349e932027c8'
down_revision: str | None = '0001_prepare_auth_schema'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('idempotency_record_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('route', sa.String(length=180), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_idempotency_records_expiry_after_creation')),
    sa.PrimaryKeyConstraint('idempotency_record_id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('actor_id', 'route', 'key_hash', name=op.f('uq_idempotency_records_actor_id')),
    schema='auth'
    )
    op.create_index('ix_idempotency_expiry', 'idempotency_records', ['expires_at'], unique=False, schema='auth')
    op.create_table('organizations',
    sa.Column('org_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=24), server_default='active', nullable=False),
    sa.Column('subscription_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('active', 'suspended', 'closed')", name=op.f('ck_organizations_state_valid')),
    sa.PrimaryKeyConstraint('org_id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug')),
    schema='auth'
    )
    op.create_table('outbox_events',
    sa.Column('outbox_event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('pending', 'processing', 'published', 'failed')", name=op.f('ck_outbox_events_state_valid')),
    sa.PrimaryKeyConstraint('outbox_event_id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_outbox_events_idempotency_key')),
    schema='auth'
    )
    op.create_index('ix_outbox_events_available', 'outbox_events', ['state', 'available_at'], unique=False, schema='auth')
    op.create_table('role_permission_catalog',
    sa.Column('catalog_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('permission', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('catalog_id', name=op.f('pk_role_permission_catalog')),
    sa.UniqueConstraint('module', 'role', 'permission', 'version', name=op.f('uq_role_permission_catalog_module')),
    schema='auth'
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('given_name', sa.String(length=120), nullable=True),
    sa.Column('family_name', sa.String(length=120), nullable=True),
    sa.Column('phone_e164', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('pending', 'active', 'locked', 'suspended', 'disabled', 'anonymized')", name=op.f('ck_users_state_valid')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    schema='auth'
    )
    op.create_index('uq_users_email_active', 'users', ['email'], unique=True, schema='auth', postgresql_where=sa.text('anonymized_at IS NULL'))
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('subject_user_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('previous_hash', sa.String(length=128), nullable=True),
    sa.Column('record_hash', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('success', 'failure', 'denied')", name=op.f('ck_audit_logs_outcome_valid')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['auth.users.user_id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['auth.organizations.org_id'], name=op.f('fk_audit_logs_org_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['auth.users.user_id'], name=op.f('fk_audit_logs_subject_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_audit_logs')),
    schema='auth'
    )
    op.create_index('ix_audit_logs_org_cursor', 'audit_logs', ['org_id', 'occurred_at', 'audit_id'], unique=False, schema='auth')
    op.create_index('ix_audit_logs_subject_cursor', 'audit_logs', ['subject_user_id', 'occurred_at', 'audit_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_audit_logs_subject_user_id'), 'audit_logs', ['subject_user_id'], unique=False, schema='auth')
    op.create_table('ephemeral_tokens',
    sa.Column('ephemeral_token_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("purpose IN ('email_verify', 'phone_verify', 'password_reset', 'invite')", name=op.f('ck_ephemeral_tokens_purpose_valid')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_ephemeral_tokens_expiry_after_creation')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], name=op.f('fk_ephemeral_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ephemeral_token_id', name=op.f('pk_ephemeral_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_ephemeral_tokens_token_hash')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_ephemeral_tokens_user_id'), 'ephemeral_tokens', ['user_id'], unique=False, schema='auth')
    op.create_index('ix_ephemeral_tokens_user_active', 'ephemeral_tokens', ['user_id', 'purpose', 'expires_at'], unique=False, schema='auth')
    op.create_table('gdpr_requests',
    sa.Column('gdpr_request_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=24), nullable=False),
    sa.Column('state', sa.String(length=24), server_default='requested', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('artifact_reference', sa.Text(), nullable=True),
    sa.Column('artifact_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.CheckConstraint("request_type IN ('export', 'erasure')", name=op.f('ck_gdpr_requests_type_valid')),
    sa.CheckConstraint("state IN ('requested', 'processing', 'completed', 'failed', 'cancelled')", name=op.f('ck_gdpr_requests_state_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], name=op.f('fk_gdpr_requests_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('gdpr_request_id', name=op.f('pk_gdpr_requests')),
    schema='auth'
    )
    op.create_index('ix_gdpr_requests_user_state', 'gdpr_requests', ['user_id', 'state'], unique=False, schema='auth')
    op.create_table('governed_requests',
    sa.Column('governed_request_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('request_type', sa.String(length=80), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('initiator_user_id', sa.UUID(), nullable=False),
    sa.Column('approver_user_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('execute_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticket_reference', sa.String(length=120), nullable=True),
    sa.Column('result_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint("state IN ('pending', 'approved', 'rejected', 'executed', 'expired', 'cancelled')", name=op.f('ck_governed_requests_state_valid')),
    sa.CheckConstraint('execute_after >= initiated_at', name=op.f('ck_governed_requests_execution_not_early')),
    sa.CheckConstraint('initiator_user_id <> approver_user_id', name=op.f('ck_governed_requests_different_actors')),
    sa.ForeignKeyConstraint(['approver_user_id'], ['auth.users.user_id'], name=op.f('fk_governed_requests_approver_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['initiator_user_id'], ['auth.users.user_id'], name=op.f('fk_governed_requests_initiator_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['auth.organizations.org_id'], name=op.f('fk_governed_requests_org_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['auth.users.user_id'], name=op.f('fk_governed_requests_target_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('governed_request_id', name=op.f('pk_governed_requests')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_governed_requests_org_id'), 'governed_requests', ['org_id'], unique=False, schema='auth')
    op.create_index('ix_governed_requests_pending', 'governed_requests', ['state', 'execute_after'], unique=False, schema='auth')
    op.create_table('identities',
    sa.Column('identity_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(provider = 'password' AND password_hash IS NOT NULL) OR (provider <> 'password' AND password_hash IS NULL)", name=op.f('ck_identities_password_hash_matches_provider')),
    sa.CheckConstraint("provider IN ('password', 'google', 'apple', 'phone')", name=op.f('ck_identities_provider_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], name=op.f('fk_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id', name=op.f('pk_identities')),
    sa.UniqueConstraint('provider', 'provider_subject', name=op.f('uq_identities_provider')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'identities', ['user_id'], unique=False, schema='auth')
    op.create_table('invitations',
    sa.Column('invitation_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('invitee_email', postgresql.CITEXT(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('proposed_roles', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('issued_by_user_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('pending', 'accepted', 'expired', 'revoked')", name=op.f('ck_invitations_state_valid')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_invitations_expiry_after_creation')),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['auth.users.user_id'], name=op.f('fk_invitations_issued_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['auth.organizations.org_id'], name=op.f('fk_invitations_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invitation_id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitations_token_hash')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_invitations_org_id'), 'invitations', ['org_id'], unique=False, schema='auth')
    op.create_index('ix_invitations_org_pending', 'invitations', ['org_id', 'state', 'expires_at'], unique=False, schema='auth')
    op.create_table('mfa_devices',
    sa.Column('mfa_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('factor_type', sa.String(length=32), nullable=False),
    sa.Column('encrypted_secret', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(factor_type IN ('totp', 'backup_codes') AND encrypted_secret IS NOT NULL) OR (factor_type NOT IN ('totp', 'backup_codes') AND encrypted_secret IS NULL)", name=op.f('ck_mfa_devices_secret_matches_factor_type')),
    sa.CheckConstraint("factor_type IN ('totp', 'sms', 'email', 'passkey', 'backup_codes')", name=op.f('ck_mfa_devices_factor_type_valid')),
    sa.CheckConstraint("status IN ('pending', 'active', 'revoked')", name=op.f('ck_mfa_devices_status_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], name=op.f('fk_mfa_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mfa_id', name=op.f('pk_mfa_devices')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_mfa_devices_user_id'), 'mfa_devices', ['user_id'], unique=False, schema='auth')
    op.create_table('refresh_token_families',
    sa.Column('family_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint_hash', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=80), nullable=True),
    sa.CheckConstraint('absolute_expires_at > created_at', name=op.f('ck_refresh_token_families_expiry_after_creation')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], name=op.f('fk_refresh_token_families_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('family_id', name=op.f('pk_refresh_token_families')),
    schema='auth'
    )
    op.create_index('ix_refresh_families_user_active', 'refresh_token_families', ['user_id', 'revoked_at'], unique=False, schema='auth')
    op.create_table('trusted_devices',
    sa.Column('trusted_device_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=128), nullable=False),
    sa.Column('trust_state', sa.String(length=24), server_default='unknown', nullable=False),
    sa.Column('last_ip_address', postgresql.INET(), nullable=True),
    sa.Column('risk_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("trust_state IN ('unknown', 'trusted', 'blocked')", name=op.f('ck_trusted_devices_state_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], name=op.f('fk_trusted_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trusted_device_id', name=op.f('pk_trusted_devices')),
    sa.UniqueConstraint('user_id', 'fingerprint_hash', name=op.f('uq_trusted_devices_user_id')),
    schema='auth'
    )
    op.create_table('user_role_bindings',
    sa.Column('binding_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['auth.role_permission_catalog.catalog_id'], name=op.f('fk_user_role_bindings_catalog_id_role_permission_catalog'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['auth.users.user_id'], name=op.f('fk_user_role_bindings_granted_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['auth.organizations.org_id'], name=op.f('fk_user_role_bindings_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], name=op.f('fk_user_role_bindings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('binding_id', name=op.f('pk_user_role_bindings')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_user_role_bindings_org_id'), 'user_role_bindings', ['org_id'], unique=False, schema='auth')
    op.create_index('uq_role_bindings_active', 'user_role_bindings', ['user_id', 'org_id', 'catalog_id'], unique=True, schema='auth', postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('password_history',
    sa.Column('history_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['auth.identities.identity_id'], name=op.f('fk_password_history_identity_id_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id', name=op.f('pk_password_history')),
    schema='auth'
    )
    op.create_index('ix_password_history_identity_created', 'password_history', ['identity_id', 'created_at'], unique=False, schema='auth')
    op.create_table('refresh_tokens',
    sa.Column('refresh_token_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expires_at > issued_at', name=op.f('ck_refresh_tokens_expiry_after_issue')),
    sa.CheckConstraint('generation >= 0', name=op.f('ck_refresh_tokens_generation_nonnegative')),
    sa.ForeignKeyConstraint(['family_id'], ['auth.refresh_token_families.family_id'], name=op.f('fk_refresh_tokens_family_id_refresh_token_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('refresh_token_id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('family_id', 'generation', name=op.f('uq_refresh_tokens_family_id')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False, schema='auth')
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('access_jti', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('device_fingerprint_hash', sa.String(length=128), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_sessions_expiry_after_creation')),
    sa.ForeignKeyConstraint(['family_id'], ['auth.refresh_token_families.family_id'], name=op.f('fk_sessions_family_id_refresh_token_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['auth.organizations.org_id'], name=op.f('fk_sessions_org_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('access_jti', name=op.f('uq_sessions_access_jti')),
    sa.UniqueConstraint('family_id', name=op.f('uq_sessions_family_id')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_sessions_org_id'), 'sessions', ['org_id'], unique=False, schema='auth')
    op.create_index('ix_sessions_org_active', 'sessions', ['org_id', 'revoked_at', 'expires_at'], unique=False, schema='auth')
    op.create_index('ix_sessions_user_active', 'sessions', ['user_id', 'revoked_at', 'expires_at'], unique=False, schema='auth')
    op.create_table('webauthn_credentials',
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('mfa_id', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('transports', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('backup_eligible', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('backup_state', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mfa_id'], ['auth.mfa_devices.mfa_id'], name=op.f('fk_webauthn_credentials_mfa_id_mfa_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('credential_id', name=op.f('pk_webauthn_credentials')),
    sa.UniqueConstraint('mfa_id', name=op.f('uq_webauthn_credentials_mfa_id')),
    schema='auth'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webauthn_credentials', schema='auth')
    op.drop_index('ix_sessions_user_active', table_name='sessions', schema='auth')
    op.drop_index('ix_sessions_org_active', table_name='sessions', schema='auth')
    op.drop_index(op.f('ix_auth_sessions_org_id'), table_name='sessions', schema='auth')
    op.drop_table('sessions', schema='auth')
    op.drop_index(op.f('ix_auth_refresh_tokens_family_id'), table_name='refresh_tokens', schema='auth')
    op.drop_table('refresh_tokens', schema='auth')
    op.drop_index('ix_password_history_identity_created', table_name='password_history', schema='auth')
    op.drop_table('password_history', schema='auth')
    op.drop_index('uq_role_bindings_active', table_name='user_role_bindings', schema='auth', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_auth_user_role_bindings_org_id'), table_name='user_role_bindings', schema='auth')
    op.drop_table('user_role_bindings', schema='auth')
    op.drop_table('trusted_devices', schema='auth')
    op.drop_index('ix_refresh_families_user_active', table_name='refresh_token_families', schema='auth')
    op.drop_table('refresh_token_families', schema='auth')
    op.drop_index(op.f('ix_auth_mfa_devices_user_id'), table_name='mfa_devices', schema='auth')
    op.drop_table('mfa_devices', schema='auth')
    op.drop_index('ix_invitations_org_pending', table_name='invitations', schema='auth')
    op.drop_index(op.f('ix_auth_invitations_org_id'), table_name='invitations', schema='auth')
    op.drop_table('invitations', schema='auth')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='identities', schema='auth')
    op.drop_table('identities', schema='auth')
    op.drop_index('ix_governed_requests_pending', table_name='governed_requests', schema='auth')
    op.drop_index(op.f('ix_auth_governed_requests_org_id'), table_name='governed_requests', schema='auth')
    op.drop_table('governed_requests', schema='auth')
    op.drop_index('ix_gdpr_requests_user_state', table_name='gdpr_requests', schema='auth')
    op.drop_table('gdpr_requests', schema='auth')
    op.drop_index('ix_ephemeral_tokens_user_active', table_name='ephemeral_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_ephemeral_tokens_user_id'), table_name='ephemeral_tokens', schema='auth')
    op.drop_table('ephemeral_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_audit_logs_subject_user_id'), table_name='audit_logs', schema='auth')
    op.drop_index(op.f('ix_auth_audit_logs_org_id'), table_name='audit_logs', schema='auth')
    op.drop_index(op.f('ix_auth_audit_logs_actor_user_id'), table_name='audit_logs', schema='auth')
    op.drop_index('ix_audit_logs_subject_cursor', table_name='audit_logs', schema='auth')
    op.drop_index('ix_audit_logs_org_cursor', table_name='audit_logs', schema='auth')
    op.drop_table('audit_logs', schema='auth')
    op.drop_index('uq_users_email_active', table_name='users', schema='auth', postgresql_where=sa.text('anonymized_at IS NULL'))
    op.drop_table('users', schema='auth')
    op.drop_table('role_permission_catalog', schema='auth')
    op.drop_index('ix_outbox_events_available', table_name='outbox_events', schema='auth')
    op.drop_table('outbox_events', schema='auth')
    op.drop_table('organizations', schema='auth')
    op.drop_index('ix_idempotency_expiry', table_name='idempotency_records', schema='auth')
    op.drop_table('idempotency_records', schema='auth')
    # ### end Alembic commands ###
